version: '2.1'
services:

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "fluffy_owner"
      POSTGRES_DB: "fluffy-broccoli"
    ports:
      - '5432:5432'
    volumes:
      - ./api/src/main/resources:/docker-entrypoint-initdb.d/

  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
       MICROSOFT_KEY: "f2a9a9f29d7d4e878669cdfed04f99ce"
       MICROSOFT_REGION: "westeurope"
       MICROSOFT_URL: "https://api-eur.cognitive.microsofttranslator.com/translate?api-version=3.0&from=nl&to=en"
